In [27]:
import pandas as pd
import numpy as np

# principals_df = pd.read_csv('./data/imdb.title.principals.csv.gz')
# basics_df = pd.read_csv('./data/imdb.name.basics.csv.gz')
# gross_df = pd.read_csv('./data/bom.movie_gross.csv.gz')
# akas_df = pd.read_csv('./data/imdb.title.akas.csv.gz')
tm_movies_db = pd.read_csv('./data/tmdb.movies.csv.gz')
# tm_movies2_db = pd.read_json('./data/tmdb.movie_ids.json.gz')

In [25]:
tm_movies_db.head(20)

,Unnamed: 0,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186
5,5,"[12, 14, 10751]",32657,en,Percy Jackson & the Olympians: The Lightning T...,26.691,2010-02-11,Percy Jackson & the Olympians: The Lightning T...,6.1,4229
6,6,"[28, 12, 14, 878]",19995,en,Avatar,26.526,2009-12-18,Avatar,7.4,18676
7,7,"[16, 10751, 35]",10193,en,Toy Story 3,24.445,2010-06-17,Toy Story 3,7.7,8340
8,8,"[16, 10751, 35]",20352,en,Despicable Me,23.673,2010-07-09,Despicable Me,7.2,10057
9,9,"[16, 28, 35, 10751, 878]",38055,en,Megamind,22.855,2010-11-04,Megamind,6.8,3635
10,10,"[16, 35, 10751]",863,en,Toy Story 2,22.698,1999-11-24,Toy Story 2,7.5,7553
11,11,"[10751, 14, 12]",12155,en,Alice in Wonderland,22.020,2010-03-05,Alice in Wonderland,6.6,8713
12,12,"[53, 12, 28]",27578,en,The Expendables,21.517,2010-08-03,The Expendables,6.1,4647
13,13,"[16, 10751]",38757,en,Tangled,21.511,2010-11-24,Tangled,7.5,6407
14,14,"[27, 80]",41439,en,Saw 3D,20.370,2010-10-28,Saw: The Final Chapter,6.0,1488
15,15,"[12, 14, 18, 10749]",24021,en,The Twilight Saga: Eclipse,20.340,2010-06-23,The Twilight Saga: Eclipse,6.0,4909
16,16,"[28, 53, 878]",20504,en,The Book of Eli,18.985,2010-01-11,The Book of Eli,6.7,3495
17,17,"[10402, 10749]",52371,nl,LelleBelle,18.586,2010-10-09,LelleBelle,4.5,36
18,18,"[28, 18, 53]",2502,en,The Bourne Supremacy,18.199,2004-07-23,The Bourne Supremacy,7.3,4367
19,19,"[18, 53, 9648]",11324,en,Shutter Island,18.060,2010-02-18,Shutter Island,8.1,12625

In [15]:
b_and_p_df = basics_df.merge(principals_df, on="nconst")

# GENERAL QUESTIONS: 

- [ ] genre frequency?
- [ ] rise in actors of color - should ms fund eg asian cast movies
- [ ] ratio of budget to box office - key metrics
- [ ] what are similarities of highest rated movies, highest grossing 
- [ ] should ms look into foreign films, markets
- [ ] does a foreign actor/studio make that film better in that country
- [ ] could ms use existing products to promote new viewing tech in the home environment (holo lense, kinect)
- [ ] number of user ratings (populist) against gross
    - [ ] how to cut through rating bias (rating vs rating count vs popularity)
- [ ] what movies perform better online than in theaters
- [ ] how to calculate VORM - what is the best way to rate success of a film
    - [ ] how do you define as the reference point

# GRAPHS:

1. rating vs ROI (return on investment) - (create net revenue vs ratings) 
2. ROI vs awards 
3. rating and budget vs investment
4. ratings vs gross revenue
5. ratings vs budget

# GOALS:

### OVERALL: 

- should ms get into the movie streaming service
- if so, what is the most profitable direction
- How can they be unique in the landscape